const sentenceList = [
  // (Initial ~150 lines from Harvard + curated examples)
  "The birch canoe slid on the smooth planks.",
  "Glue the sheet to the dark blue background.",
  "It's easy to tell the depth of a well.",
  "These days a chicken leg is a rare dish.",
  "Rice is often served in round bowls.",
  "The juice of lemons makes fine punch.",
  "The box was thrown beside the parked truck.",
  "The hogs were fed chopped corn and garbage.",
  "Four hours of steady work faced us.",
  "A large size in stockings is hard to sell.",
  "The boy was there when the sun rose.",
  "A rod is used to catch pink salmon.",
  "The source of the huge river is the clear spring.",
  "Kick the ball straight and follow through.",
  "Help the woman get back to her feet.",
  "A pot of tea helps to pass the evening.",
  "Smoky fires lack flame and heat.",
  "The soft cushion broke the man's fall.",
  "The salt breeze came across from the sea.",
  "The girl at the booth sold fifty bonds.",
  "The small pup gnawed a hole in the sock.",
  "The fish twisted and turned on the bent hook.",
  "Press the pants and sew a button on the vest.",
  "The swan dive was far short of perfect.",
  "The beauty of the view stunned the young boy.",
  "Two blue fish swam in the tank.",
  "Her purse was full of useless trash.",
  "The colt reared and threw the tall rider.",
  "It snowed, rained, and hailed the same morning.",
  "Read verse out loud for pleasure.",
  "The store walls were lined with colored frocks.",
  "The peace league met to discuss their plans.",
  "Paper is scarce, so write with much care.",
  "The quick fox jumped on the sleeping cat.",
  "The nozzle of the fire hose was bright brass.",
  "Screw the round cap on as tight as needed.",
  "Time brings us many changes.",
  "The purple tie was ten years old.",
  "Men think and plan and sometimes act.",
  "Fill the ink jar with sticky glue.",
  "We need grain to keep our mules healthy.",
  "The crunch of feet in the snow was the only sound.",
  "The copper bowl shone in the sun's rays.",
  "Boards will warp unless kept dry.",
  "Nine rows of soldiers stood in line.",
  "The beach is dry and shallow at low tide.",
  "The kitten chased the dog down the street.",
  "Try to trace the fine lines of the painting.",
  "Women form less than half of the group.",
  "The zones merge in the central part of town.",
  "A gem in the rough needs work to polish.",
  "Code is used when secrets are sent.",
  "Most of the news is easy for us to hear.",
  "He used the lathe to make brass objects.",
  "The vane on top of the pole revolved in the wind.",
  "Mince pie is a dish served to children.",
  "The clan gathered on each dull night.",
  "Let it burn, it gives us warmth and comfort.",
  "A castle built from sand fails to endure.",
  "A child's wit saved the day for us.",
  "Tack the strip of carpet to the worn floor.",
  "Next Tuesday we must vote.",
  "The little tales they tell are false.",
  "The door was barred, locked, and bolted as well.",
  "Ripe pears are fit for a queen's table.",
  "A big wet stain was on the round carpet.",
  "The kite dipped and swayed, but stayed aloft.",
  "The pleasant hours fly by much too soon.",
  "The room was crowded with a wild mob.",
  "This strong arm shall shield your honor.",
  "Press the pedal with your left foot.",
  "Neat plans fail without luck.",
  "The black trunk fell from the landing.",
  "The theft of the pearl pin was kept secret.",
  "Shake hands with this friendly child.",
  "The vast space stretched into the far distance.",
  "A rich farm is rare in this sandy waste.",
  "His wide grin earned many friends.",
  "Flax makes a fine brand of paper.",
  "Hurdle the pit with the aid of a long pole.",
  "A strong bid may scare your partner stiff.",
  "Even a just cause needs power to win.",
  "Peep under the tent and see the clowns.",
  "Cheap clothes are flashy but don't last.",
  "Flood the mails with requests for this book.",
  "A thick coat of black paint covered all.",
  "The pencil was cut to be sharp at both ends.",
  "Those last words were a strong statement.",
  "He wrote his name boldly at the top of the sheet.",
  "Dill pickles are sour but taste fine.",
  "Either mud or dust are found at all times.",
  "The best method is to fix it in place with clips.",
  "If you mumble your speech will be lost.",
  "At night the alarm roused him from a deep sleep.",
  "Tear a thin sheet from the yellow pad.",
  "A streak of color ran down the left edge.",
  "Crouch before you jump or miss the mark.",
  "The square peg will settle in the round hole.",
  "Fine soap saves tender skin.",
  "Poached eggs and tea must suffice.",
  "Bad nerves are jangled by a door slam.",
  "The fruit of a fig tree is apple-shaped.",
  "Corn cobs can be used to kindle a fire.",
  "Where were they when the noise started.",
  "The paper box is full of thumb tacks.",
  "Sell your gift to a buyer at a good gain.",
  "The tongs lay beside the ice pail.",
  "The petals fall with the next puff of wind.",
  "A blue crane is a tall wading bird.",
  "A fresh start will work such wonders.",
  "The counselor taught the new maid to serve.",
  "She was kind to sick old people.",
  "The dusty bench stood by the stone wall.",
  "Smile when you say nasty words.",
  "The water in this well is a source of good health.",
  "Stop whistling and watch the boys march.",
  "Jerk the cord, and out tumbles the gold.",
  "The cloud moved in a stately way and was gone.",
  "Light maple makes for a swell room.",
  "Cap the jar with a tight brass cover.",
  "The sink is the thing in which we pile dishes.",
  "A whiff of it will cure the most stubborn cold.",
  "Oak is strong and also gives shade.",
  "Cats and dogs each hate the other.",
  "Open the crate but don’t break the glass.",
  "Add the sum to the product of these three.",
  "Thieves who rob friends deserve jail.",
  "The ripe taste of cheese improves with age.",
  "Act on these orders with great speed.",
  "The hog crawled under the high fence.",
  "Move the vat over the hot fire.",
  "The bark of the pine tree was shiny and dark.",
  "Leaves turn brown and yellow in the fall.",
  "Split the log with a quick, sharp blow.",
  "Burn peat after the logs give out.",
  "He ordered peach pie with ice cream.",
  "Weave the carpet on the right hand side.",
  "Hemp is a weed found in parts of the tropics.",
  "A lame back kept his score low.",
  "We find joy in the simplest things.",
  "The orchestra tuned quietly before the concert began.",
  "A brilliant orange sunset spread across the horizon.",
  "He delicately balanced the teacup on the saucer.",
  "She read the old letter by the amber lamp.",
  "A gentle snowfall covered the ground in a soft blanket.",
  "The distant mountains were capped with pure white snow.",
  "He tasted the soup and added a pinch of salt.",
  "The children giggled as they splashed in puddles.",
  "The clock chimed midnight, announcing the new day.",
  "She slid the key silently into the ancient door.",
  "Olive trees lined the winding path along the hillside.",
  "He sketched the outline of the old oak tree.",
  "The bakery windows were filled with golden pastries.",
  "Fog rolled lazily over the calm lake at dawn.",
  "She tied the ribbon tightly around the gift box.",
  "The steam rose in spirals from the hot coffee mug.",
  "A pair of swallows darted across the twilight sky.",
  "He thanked the librarian and quietly left the room.",
  "The roses in the garden smelled sweet and heady.",
  "She hummed a lullaby as she rocked the cradle.",
  "A single candle flickered in the otherwise dark room.",
  "He watched the ship sail slowly down the river.",
  "The piano notes drifted softly into the empty hall.",
  "Snowflakes melted on the warm stone steps.",
  "Children built a snowman with carrot nose and scarf.",
  "He closed his eyes and listened to the distant thunder.",
  "The porch light cast long shadows on the walkway.",
  "She gently smoothed the wrinkles from the old quilt.",
  "A flock of geese flew in a perfect V formation overhead.",
  "He felt a sense of calm as the waves lapped the shore.",
  "The moon peeked through the branches of the tall pine trees.",
  "She added a fresh sprig of mint to the iced tea.",
  "He polished the antique brass lantern until it gleamed.",
  "The bookstore had a cozy corner filled with armchairs.",
  "Dewdrops clung to the petals of the early morning flower.",
  "He adjusted his glasses and continued to read the fine print.",
  "She pinned a map to the corkboard above her desk.",
  "The old bicycle stood rusting against the wooden fence.",
  "He stirred the pot of stew with a wooden spoon.",
  "The distant whistle of a train echoed in the night.",
  "She tied her shoelaces before starting the morning run.",
  "The aroma of coffee drifted through the quiet kitchen.",
  "He watched the flames dance in the crackling fireplace.",
  "She brushed the crumbs from the kitchen table.",
  "The field was ablaze with the color of wildflowers.",
  "He placed the antique vase gently on the mantle.",
  "The library smelled of old books and polished wood.",
  "She sketched the silhouette of the city skyline at dusk.",
  "He unwrapped the chocolate and took a slow bite.",
  "The telephone rang sharply in the silent house.",
  "She adjusted the knobs on the old radio set.",
  "He walked slowly beneath the canopy of autumn leaves.",
  "She gathered shells along the sandy shoreline.",
  "The campfire crackled and popped in the cool evening air.",
  "He traced the constellations on the clear summer night.",
  "She folded the paper into a tiny boat and set it afloat.",
  "The barn door creaked open at first light.",
  "He polished his shoes until they gleamed like mirrors.",
  "She planted seeds in neat rows under the warm sun.",
  "The wind chimes tinkled softly in the gentle breeze.",
  "He clipped the coupon before it expired tomorrow.",
  "She draped the scarf over her shoulders to keep warm.",
  "He saved the receipt for his records and filed it away.",
  "She painted the canvas in bold, colorful strokes.",
  "The old clock on the wall ticked steadily forward.",
  "He weighed the fruit before placing it in the basket.",
  "She measured the fabric for the dress she intended to make.",
  "He loaded the truck with care before setting off.",
  "She pressed her hand against the cold glass window.",
  "They danced slowly beneath the glittering chandelier.",
  "He recorded the lecture on his small digital recorder.",
  "She carried the tray of glasses to the dining table.",
  "He wiped the fog off the mirror before shaving.",
  "She folded the letter and slipped it into an envelope.",
  "The candlelight reflected off the crystal vase on the table.",
  "He drew a deep breath and stepped onto the stage.",
  "She swept the porch until it gleamed in the morning sun.",
  "He balanced the books on the unstable shelf carefully.",
  "She fed the ducks at the park pond every Sunday morning.",
  "He secured the boat to the dock with a strong rope.",
  "She jotted notes in the margin of her notebook.",
  "He tightened the screws on the loose chair leg.",
  "She pressed flowers into the pages of her leather journal.",
  "He tasted the freshly baked bread for seasoning.",
  "She arranged the vegetables neatly on the chopping board.",
  "He adjusted the focus of the telescope before nightfall.",
  "She packed her bag quickly for the early morning trip.",
  "He tuned the guitar before starting to play.",
  "She lit the incense and closed her eyes in meditation.",
  "He watered each plant with a careful drizzle.",
  "She brushed the dust off the ancient photo album.",
  "He waited patiently as the kettle reached a rolling boil.",
  "She buttoned up the cardigan before heading outside.",
  "He folded the map and tucked it into his pocket.",
  "She tested the light switch before repairing it.",
  "He clipped the hedges into neat geometric shapes.",
  "She polished the wooden floors until they shone.",
  "He hammered the nail into the wall with steady rhythm.",
  "She whispered a secret into the summer breeze.",
  "He navigated the narrow path around the grand estate.",
  "The mountain peak looked breathtaking under the full moon.",
  "She arranged fresh flowers on the kitchen counter.",
  "A lone seagull circled above the sleepy harbor.",
  "He scribbled a note and tucked it into his pocket.",
  "The children chased bubbles in the morning sunlight.",
  "She folded the blanket and smoothed out each wrinkle.",
  "He paused to admire the intricate carvings on the door.",
  "The old oak tree shaded the picnic table below.",
  "She painted the shutters a bright shade of teal.",
  "He polished the silverware until it gleamed beautifully.",
  "The violin's melody drifted through the open window.",
  "She read aloud from the old leather-bound journal.",
  "He watched the raindrops race down the foggy glass.",
  "The antique clock chimed three times in the empty house.",
  "She wore a necklace made of tiny sea glass beads.",
  "He pressed his ear to the shell and heard the ocean.",
  "The scent of pine filled the air after the storm.",
  "She planted tulips along the winding garden path.",
  "He traced the map with a trembling fingertip.",
  "The bookstore was quiet except for soft footsteps.",
  "She packed sandwiches and lemonade for their hike.",
  "He sketched the silhouette of the old barn.",
  "A cool wind rustled the pages of her notebook.",
  "He wrung out his coat and hung it by the fire.",
  "She counted constellations on the clear summer night.",
  "He laughed as his dog bounded across the field.",
  "The scent of roses drifted through the open gate.",
  "She cooked a hearty stew with fresh vegetables from the garden.",
  "He tied the ribbon in a perfect bow around the package.",
  "The theater lights dimmed and the audience hushed.",
  "She pressed a daisy into the pages of her poetry book.",
  "He balanced on the boardwalk overlooking the waves.",
  "The smell of cinnamon and sugar filled the bakery.",
  "She carried a small lantern down the dark corridor.",
  "He fitted the new key into the ancient lock.",
  "The parchment crackled as she unfolded it carefully.",
  "She watched the candle flame flicker in the draft.",
  "He lined up his books on the wooden shelf.",
  "The rain pattered softly on the tin rooftop.",
  "She clipped a coupon from the newspaper before shopping.",
  "He rocked gently in the old rocking chair by the window.",
  "The meadow glowed with fireflies at dusk.",
  "She listened to the crackle of autumn leaves underfoot.",
  "He painted the entire room in a crisp shade of white.",
  "The campfire lit up their smiling faces in the dark.",
  "She washed the berries and set them in a bowl.",
  "He fastened the collar of his crisp dress shirt.",
  "The parchment was adorned with elegant calligraphy.",
  "She clipped the leash to her dog's ornate collar.",
  "He clicked the volume down before the speech.",
  "The hammock swayed gently in the summer breeze.",
  "She stretched out on the grass to watch the clouds.",
  "He picked a ripe apple from the orchard tree.",
  "The wooden bridge spanned across the quiet creek.",
  "She wrapped the scarf snugly around her neck.",
  "He fed the goldfish just as the sun rose.",
  "The scent of fresh paint lingered in the room.",
  "She wrote her name carefully at the top of the test.",
  "He closed the drawer and slid the key inside.",
  "The scent of fresh baked bread filled the hall.",
  "She placed the photo in a silver frame on the mantel.",
  "He wound the mechanical clock before bedtime.",
  "The tapestry on the wall depicted a pastoral scene.",
  "She brewed mint tea in a delicate porcelain cup.",
  "He tied the boat back to the weathered dock.",
  "The pages of the magazine were filled with vibrant photos.",
  "She wore gloves to protect her hands in the garden.",
  "He carried the heavy bag with determined steps.",
  "The violin case lay open beside the music stand.",
  "She sorted the letters by date and sender.",
  "He installed the new bulb in the antique lamp.",
  "The scent of lavender drifted through the linen closet.",
  "She folded her clothes neatly into the dresser drawers.",
  "He unrolled the blueprint across the workbench.",
  "The bright tapestry covered the old wooden chair.",
  "She sipped her coffee slowly at dawn.",
  "He locked the door and pocketed the key.",
  "The dusty attic held memories of years gone by.",
  "She traced her finger along the written line.",
  "He polished the leather shoes until they shone.",
  "The fireplace crackled as new logs were added.",
  "She gazed at her reflection in the antique mirror.",
  "He swept the hearth clean before lighting the fire.",
  "The curtain fluttered as a breeze came through the window.",
  "She tried on the new hat in front of the mirror.",
  "He skipped stones across the calm lake surface.",
  "The library's wooden shelves towered to the ceiling.",
  "She knitted a scarf using yarn of vibrant colors.",
  "He placed the chess piece with careful precision.",
  "The rain-slicked road glistened under the streetlight.",
  "She pressed flowers between the pages of her diary.",
  "He tuned the piano by ear late into the night.",
  "The cat purred softly as she stroked its fur.",
  "She let the fabric hang to dry in the sun.",
  "He stirred the stew with a heavy ladle.",
  "The poster on the wall depicted a colorful festival.",
  "She draped a shawl over her shoulders against the chill.",
  "He polished the brass doorknob multiple times until it gleamed.",
    "The orchard trees burst into bloom under the warm spring sun.",
  "She balanced on one foot while tying her shoelace with grace.",
  "He glanced out the window at the gathering thunderclouds.",
  "The porcelain teacup trembled in her delicate hands.",
  "She draped curtains of lavender silk across the tall windows.",
  "He adjusted the telescope to focus on the distant galaxy.",
  "The echo of footsteps reverberated through the marble hallway.",
  "She traced the elegant script on the back of the old photograph.",
  "He sharpened the pencil until the lead was razor-thin.",
  "The aroma of fresh basil filled the cozy kitchen.",
  "She stamped the envelope with a bright red seal.",
  "He pressed his palm against the cool stone wall to steady himself.",
  "The ribbons fluttered in the breeze atop the decorative arch.",
  "She listened to the distant sound of church bells at dawn.",
  "He unfolded the nautical chart and plotted their next course.",
  "The fabric shimmered as she brushed it beneath the light.",
  "She traced constellations on the globe before bed.",
  "He scooped vanilla ice cream into a delicate sugar cone.",
  "The horses trotted rhythmically across the sunlit meadow.",
  "She sketched the sailboat drifting on the tranquil bay.",
  "He poured sparkling water into his crystal glass.",
  "The melody of the old harp drifted through the open window.",
  "She tucked a sprig of rosemary behind her ear.",
  "He lined up glass bottles along the windowsill for sunlight.",
  "The velvet blanket kept the newborn kitten warmly nestled.",
  "She brushed off pine needles after her walk in the woods.",
  "He slid the paper across the desk for her to sign.",
  "The leather-bound journal lay open on the oak writing desk.",
  "She stenciled bright geometrical patterns onto the canvas.",
  "He clipped a freshly bloomed lily into the flower vase.",
  "The helicopter’s rotors stirred up dust across the airstrip.",
  "She wrapped the yarn tightly around the wooden spindle.",
  "He paused to admire the stained-glass window at the chapel.",
  "The lighthouse beam swept across the calm evening ocean.",
  "She sketched clouds drifting by in quick charcoal strokes.",
  "He closed the old chest with a heavy thud.",
  "The meadow was dotted with daisies and dandelions.",
  "She listened closely to the soft sound of the violin.",
  "He gingerly carried the porcelain figurine across the room.",
  "The evening mist rolled in over the silent hills.",
  "She adjusted the vintage camera and clicked the shutter.",
  "He carved a small boat from a piece of driftwood.",
  "The old stone bridge arched over the tranquil stream.",
  "She spread maples leaves across the autumn walkway.",
  "He swung the lantern to light the narrow corridor.",
  "The straw hat shaded her face from the midday sun.",
  "She perched on the dock’s edge, dangling her bare feet.",
  "He scribbled his thoughts into the pocket notebook.",
  "The steam from the hot cup swirled in the frosty air.",
  "She stitched a patch onto the brown canvas backpack.",
  "He tightened the spokes on the ancient bicycle wheel.",
  "The ivy climbed gracefully up the brick wall outside.",
  "She picked a handful of wild strawberries from the field.",
  "He balanced the stack of dishes on one arm.",
  "The carousel horses shimmered under glowing string lights.",
  "She folded a paper crane while humming softly.",
  "He traced the ornate border of the antique mirror frame.",
  "The aroma of cinnamon rolls wafted from the kitchen window.",
  "She hung lanterns of soft silk from the balcony rails.",
  "He brushed the dust from the glossy bookshelf surfaces.",
  "The summer wind rustled the curtains in the open window.",
  "She draped the autumn wreath over the red door.",
  "He penciled grid lines neatly across the yellow ledger sheet.",
  "The alabaster statue gleamed in the midday sun.",
  "She sketched villas along the scenic coastal highway.",
  "He strummed softly on the twelve-string guitar at dusk.",
  "The campfire’s glow reflected in their excited eyes.",
  "She threaded the needle with surprising ease.",
  "He loosened the rusted bolt from the ancient hinge.",
  "The orchard’s white blossoms rustled in the gentle breeze.",
  "She planted lavender beside the stone garden path.",
  "He grilled corn ears until they were perfectly charred.",
  "The steeple clock struck each hour with a deep chime.",
  "She arranged seashells on the edge of the sand castle.",
  "He unfolded the sail and pulled the rope taut.",
  "The delicate pastry glistened under the bakery’s lights.",
  "She traced her palm lines in the sand at low tide.",
  "He read poetry aloud beside the crackling bonfire.",
  "The dewdrops reflected the morning sun on the grass.",
  "She clipped her hair back before painting the mural.",
  "He sketched her silhouette by the window light.",
  "The aroma of roasted coffee beans filled the studio.",
  "She arranged vintage postcards in a decorative frame.",
  "He simmered tomato sauce in the small cast-iron pot.",
  "The cathedral’s stone floor felt cool beneath her feet.",
  "She pressed petals into a journal as keepsakes.",
  "He balanced his coffee cup on a saucer and sipped slowly.",
  "The humming of bees filled the fragrant summer garden.",
  "She braided her sister’s hair in the soft afternoon sun.",
  "He clipped the sail to secure it against the wind.",
  "The velvet curtains muted the afternoon light gently.",
  "She adjusted the old radio dial to find a station.",
  "He polished the surfboard before heading out to ride waves.",
  "The garden gate creaked as she walked inside.",
  "She filled the bird feeder with bright sunflower seeds.",
  "He strummed chords slowly under the starlit sky.",
  "The antique clock’s pendulum swung with steady rhythm.",
  "She stirred honey into her warm morning tea.",
  "He brushed his jacket free of sand before entering.",
  "The paper lanterns bobbed in the cool evening breeze.",
  "She hung her coat on the wrought-iron coat rack.",
  "He sketched the contours of her face carefully.",
  "The wooden floorboards groaned under his heavy footsteps.",
  "She slipped on mittens before going outside.",
  "He flipped pages gently so as not to tear them.",
  "The spiral staircase wound up into the dim loft.",
  "She placed a candle inside the carved pumpkin.",
  "He balanced on the beam as the crowd watched.",
  "The rain-soaked leaves clung to the garden path.",
  "She traced the skyline with quick strokes of paint.",
  "He tightened his grip on the surfboard leash.",
  "The cozy cabin smelled of pine and woodsmoke.",
  "She packed a picnic basket with fresh fruit and cheese.",
  "He adjusted the rearview mirror before driving off.",
  "The pond reflected the swaying reeds around it.",
  "She traced a heart in the fogged-up windowpane.",
  "He tuned the radio until a familiar song played.",
  "The rusty mailbox stood at the edge of the gravel road.",
  "She framed her photograph with a thin black border.",
  "He wrote her name on the first page of the notebook.",
  "The trail wound through the canopy of tall oak trees.",
  "She painted the wooden fence in pastel pink color.",
  "He polished the lens of his binoculars before looking.",
  "The full moon hung low above the silent lake.",
  "She harvested ripe tomatoes from the vegetable patch.",
  "He sharpened the chef's knife before preparing the meal.",
  "The windmill’s blades turned rhythmically in the wind.",
  "She carried a wicker basket filled with fresh berries.",
  "He soaked his aching feet in warm herbal water.",
  "The wooden sign creaked on its rusty hinge.",
  "She traced patterns in the cool evening sand.",
  "He wrote his message on the frosted mirror surface.",
  "The camp stove simmered with a comforting warmth.",
  "She wrapped a soft blanket around her shoulders.",
  "He brushed crumbs into his palm before eating.",
  "The pond’s surface mirrored the afternoon clouds.",
  "She arranged her knitting needles on the side table.",
  "He opened the barn door to let in fresh air.",
  "The canvas tent shivered under the crisp breeze.",
  "She placed a bookmark in the open novel before bed.",
  "He strung lanterns around the patio for the evening party.",
  "The bell tower’s chime echoed through the town square.",
  "She tasted the sweet honey dripping from the comb.",
  "He closed the violin case after playing under the tree.",
    "The moonlight streamed through the tall stained glass windows.",
  "She carefully poured the batter into the greased pan.",
  "He arranged the tools neatly across the wooden bench.",
  "The gentle rustling of the trees calmed her nerves.",
  "She set the old record on the turntable and smiled.",
  "He followed the gravel path deeper into the forest.",
  "The faint scent of jasmine lingered in the warm air.",
  "She closed the photo album with a soft sigh.",
  "He poured sand from his shoes after the long walk.",
  "The golden retriever dozed peacefully by the fireplace.",
  "She hung fairy lights around the headboard of her bed.",
  "He placed the cup of tea gently on the saucer.",
  "The candlelight flickered across the rustic wooden table.",
  "She swept the porch clean before the guests arrived.",
  "He pulled the sleeves of his sweater down over his hands.",
  "The wind carried the sound of distant chimes.",
  "She stored the apples in a woven wicker basket.",
  "He gently stroked the feathers of the injured bird.",
  "The clouds moved slowly across the pale blue sky.",
  "She dropped pebbles into the shallow creek for fun.",
  "He leaned back in his chair, eyes closed in thought.",
  "The quilt was stitched with care and filled with stories.",
  "She traced her initials into the dew-covered car window.",
  "He soaked the paintbrush and tapped it against the jar.",
  "The snow blanketed the rooftops in pure white silence.",
  "She wrapped the gift with gold paper and tied it with a bow.",
  "He polished the wood until it glowed under the light.",
  "The sound of laughter echoed through the hallways.",
  "She held the seashell to her ear and smiled.",
  "He folded the letter carefully and tucked it into a drawer.",
  "The curtains danced as the breeze slipped through the cracks.",
  "She placed a lavender sachet beneath her pillow for calm sleep.",
  "He arranged the chessboard and waited for his opponent.",
  "The flames crackled and popped as the logs settled.",
  "She dusted the windowsill and watered the plants beside it.",
  "He opened the ancient book, its pages brittle and yellowed.",
  "The gravel crunched beneath his hiking boots.",
  "She hung her hat on the wall hook by the door.",
  "He caught the falling leaf before it hit the ground.",
  "The hallway smelled of cinnamon and freshly baked bread.",
  "She buttoned her coat and stepped out into the rain.",
  "He folded the paper airplane and launched it across the room.",
  "The teapot whistled as the water began to boil.",
  "She lit a stick of incense and let the smoke curl upward.",
  "He wiped the window clean with a soft cloth.",
  "The ducks paddled lazily across the pond’s surface.",
  "She leaned her head on his shoulder without a word.",
  "He tossed a log onto the fire and watched it spark.",
  "The sunset painted the sky in shades of orange and pink.",
  "She dipped the brush in water and softened the colors.",
  "He shook the snow from his scarf before hanging it up.",
  "The shadows grew longer as evening approached.",
  "She poured warm syrup over the pancakes with care.",
  "He placed the crystal carefully back in its velvet case.",
  "The attic was filled with forgotten memories and dust.",
  "She hung photographs from clothespins on a twine line.",
  "He arranged the firewood in a perfect stack.",
  "The air smelled sweet with blooming lilacs nearby.",
  "She tucked a blanket around her sleeping child.",
  "He swept fallen petals from the garden path.",
  "The thunder rumbled low in the distance.",
  "She walked barefoot through the wet grass.",
  "He lit a lantern and set it on the porch rail.",
  "The steam rose from the bowl of hot soup.",
  "She scribbled thoughts into her spiral notebook.",
  "He leaned on the railing and watched the waves crash.",
  "The baby giggled as bubbles floated by.",
  "She folded the napkins into decorative fans.",
  "He added chopped herbs to the sizzling pan.",
  "The pine needles crunched softly under her boots.",
  "She rolled out dough on the floured counter.",
  "He tied the laces of his running shoes tightly.",
  "The fog made the streetlights glow like orbs.",
  "She whispered a wish into the wind.",
  "He ran his fingers over the embossed leather cover.",
  "The lemonade pitcher sweated on the hot summer table.",
  "She adjusted her glasses and smiled at the page.",
  "He turned the page slowly, absorbed in the story.",
  "The leaves rustled like whispers overhead.",
  "She dipped her toes into the cold mountain stream.",
  "He wrote her name in the sand and watched the tide wash it away.",
  "The hammock rocked gently between the trees.",
  "She plucked the petals one by one in silence.",
  "He poured hot tea into the porcelain cup carefully.",
  "The staircase creaked with every cautious step.",
  "She packed the last of her things into the suitcase.",
  "He tucked a note under the windshield wiper.",
  "The pond rippled as a fish broke the surface.",
  "She painted tiny stars across the night-sky mural.",
  "He zipped up his jacket and pulled on his gloves.",
  "The paper rustled as she unfolded the map.",
  "She clutched the bouquet and stepped onto the stage.",
  "He arranged the colored pencils in perfect order.",
  "The breeze carried scents of salt and seaweed.",
  "She hummed softly while stirring the batter.",
  "He buttoned the last button on his collar.",
  "The path twisted through ferns and mossy stones.",
  "She polished the silver tray until it gleamed.",
  "He lit the match and watched the candle catch fire.",
  "The dog barked playfully at the falling snowflakes.",
  "She picked ripe strawberries from the garden rows.",
  "He carved initials into the bark of a tree.",
  "The sky shifted from pink to indigo as twilight fell.",
  "She zipped the bag and slung it over her shoulder.",
  "He placed his hand on the cool stone gravestone.",
  "The sound of pages flipping echoed in the quiet room.",
  "She tied her apron around her waist and began to bake.",
  "He shook the thermos and heard the coffee slosh inside.",
  "The distant bell tower rang twelve sharp notes.",
  "She framed her favorite photo and placed it by the bed.",
  "He turned the compass and aligned it with the map.",
  "The fountain burbled gently in the town square.",
  "She slid the record into its sleeve with care.",
  "He removed his muddy boots at the door.",
  "The warm wind played with her untied hair.",
  "She wrapped the sandwiches in parchment paper.",
  "He replaced the old bulb with a brighter one.",
  "The church pews creaked as the guests sat down.",
  "She planted a kiss on the child’s forehead.",
  "He fastened the buckle of his weathered backpack.",
  "The log split with a sharp crack under the axe.",
  "She turned the dial until music filled the room.",
  "He traced the carvings on the tree trunk gently.",
  "The smell of garlic and herbs filled the air.",
  "She braided her hair with colorful ribbons.",
  "He folded the tarp and stored it under the bench.",
  "The neon sign buzzed in the late night fog.",
  "She opened the shutters and let the sun spill in.",
  "He straightened the frame that hung slightly crooked.",
  "The canoe rocked gently as she stepped inside.",
  "She traced circles in her coffee with a spoon.",
  "He opened the thermos and poured steaming tea.",
  "The scent of fresh paint lingered in the hallway.",
  "She arranged candles along the bathtub’s edge.",
  "He wrapped the scarf around his neck twice.",
  "The shovel bit into the hard-packed earth.",
  "She filled the watering can from the old pump.",
  "He added a few more logs to the dwindling fire.",
  "The bus rolled slowly through the quiet village.",
  "She stuck a note to the fridge with a magnet.",
  "He stepped into the canoe and pushed off the dock.",
  "The flashlight beam danced along the cave walls.",
  "She gathered pinecones into a small cloth bag.",
  "He brushed snow from the windshield with his sleeve.",
  "The bell on the shop door jingled as she entered.",
  "She folded each towel into a perfect square.",
  "He propped the door open with a stack of books.",
  "The stars blinked one by one into the night sky.",
  "She fastened the necklace clasp behind her neck.",
  "He tapped the compass and waited for it to settle.",
  "The candle wax dripped slowly down the side.",
  "She tucked the loose strand of hair behind her ear.",
  "He opened the blinds and watched the sunrise.",
  "The forest glowed with golden light at sunset.",
  "She blew out the candle and made a quiet wish.",
];


export default sentenceList;
